# Generated by Django 4.1.5 on 2023-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_car_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.CharField(default=1, max_length=244, verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
